import UsersController from '../controller/UsersController';
import express from 'express';
import { authenToken } from '../middleware/authenToken';
const UsersRouter = express.Router();
UsersRouter.use(authenToken);
UsersRouter.get('/getAllUsers', UsersController.getListUser);
UsersRouter.get('/getUserById/:id', UsersController.getUserById);
UsersRouter.get('/getUserByEmail', UsersController.getUserByEmail);
UsersRouter.post('/addUser', UsersController.addUser);
UsersRouter.delete('/removeUserById/:id', UsersController.removeUser);
export default UsersRouter;
